
AllCops:
  Exclude:
    - spec/fixtures/ruby_error.rb

# changed config ---------------------------

AlignHash:
  EnforcedHashRocketStyle: table

LineLength:
  Max: 119

AccessModifierIndentation:
  EnforcedStyle: outdent

DotPosition:
  EnforcedStyle: trailing

MethodLength:
  Enabled: true
  CountComments: false # count full line comments?
  Max: 10
  Severity: refactor

FileName:
  Exclude:
    - 'lib/templates/pre-commit'
    - '.codeqa.rb'

# Disabled cops ------------------------------

DoubleNegation:
  Enabled: false

ClassLength:
  Enabled: false
  CountComments: false # count full line comments?
  Max: 100

# complains about use of class vars
ClassVars:
  Enabled: false

# checks for top-level docu of classes and modules
Documentation:
  Enabled: false

# checks to avoid \1 in regex
PerlBackrefs:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

RegexpLiteral:
 Enabled: false
