Exclude:
  - 'vendor/**/*'

CheckErb:
  Enabled: true
  Engine: Erb
CheckErbHtml:
  Enabled: true
CheckRubySyntax:
  Enabled: true
RubocopLint:
  Enabled: false
CheckStrangeChars:
  Enabled: true
CheckUtf8Encoding:
  Enabled: true
CheckYard:
  Enabled: false
CheckConflict:
  Enabled: true
CheckLinkto:
  Enabled: true
CheckPry:
  Enabled: true
CheckRspecFocus:
  Enabled: true
