Exclude:
  - 'vendor/**/*'

CheckErb:
  Enabled: true
CheckErbHtml:
  Enabled: true
CheckLinkto:
  Enabled: true
CheckRubySyntax:
  Enabled: false
RubocopLint:
  Enabled: true
CheckStrangeChars:
  Enabled: true
CheckUtf8Encoding:
  Enabled: true
CheckYard:
  Enabled: true
CheckConflict:
  Enabled: true